version: "3"

services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    #Uncomment below to persist data on host disk
    #volumes:
    #  - /home/user/isu-corp-test/data/mysql:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=test --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 20s
      retries: 10

  web:
    build: .
    ports:
      - 5000:80
    depends_on:
      mysql:
        condition: service_healthy

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql:3306
